name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: toggleterm
          description: persist and toggle multiple terminals
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(ci): auto generate docs"
          branch: ${{ github.head_ref }}
